IF DB_ID('practica_api') IS NULL
  CREATE DATABASE practica_api;
GO

USE practica_api;
GO

IF OBJECT_ID('dbo.users', 'U') IS NULL
CREATE TABLE users (
  id INT IDENTITY(1,1) PRIMARY KEY,
  nombre NVARCHAR(100) NOT NULL,
  email NVARCHAR(150) NOT NULL UNIQUE,
  password NVARCHAR(255) NOT NULL,
  created_at DATETIME2 NOT NULL DEFAULT SYSDATETIME()
);
GO

IF OBJECT_ID('dbo.contactos', 'U') IS NULL
CREATE TABLE contactos (
  id INT IDENTITY(1,1) PRIMARY KEY,
  metodo NVARCHAR(20) NOT NULL,
  email NVARCHAR(150) NULL,
  telefono NVARCHAR(20) NULL,
  pais NVARCHAR(10) NULL,
  region NVARCHAR(20) NULL,
  created_at DATETIME2 NOT NULL DEFAULT SYSDATETIME()
);
GO
